-- SQL tạo bảng `online_orders` cho Supabase / PostgreSQL
-- Thực hiện trong SQL editor của Supabase hoặc psql

CREATE TABLE IF NOT EXISTS public.online_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_phone text,
  product_name text NOT NULL,
  price numeric(12, 0) NOT NULL,
  reward_points integer DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_online_orders_status ON public.online_orders (status);
CREATE INDEX IF NOT EXISTS idx_online_orders_customer_phone ON public.online_orders (customer_phone);

-- Trigger update timestamp khi row thay đổi
CREATE OR REPLACE FUNCTION public.online_orders_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_online_orders_updated_at ON public.online_orders;
CREATE TRIGGER trg_online_orders_updated_at
BEFORE UPDATE ON public.online_orders
FOR EACH ROW EXECUTE FUNCTION public.online_orders_updated_at();
