 -- Supabase / PostgreSQL schema for SPA app
-- Use in Supabase SQL editor or psql

DROP TABLE IF EXISTS public.settings CASCADE;
CREATE TABLE public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spaName text NOT NULL,
  address text,
  phone text,
  footerNote text,
  defaultBaseSalary integer DEFAULT 6000000,
  defaultServiceComm integer DEFAULT 10,
  defaultConsultComm integer DEFAULT 5,
  packagePointRate integer DEFAULT 1,
  productPointRate integer DEFAULT 1,
  referralPoints integer DEFAULT 500,
  referralStocks integer DEFAULT 200,
  currencySymbol text DEFAULT 'đ',
  taxRate integer DEFAULT 10,
  reminderLeadTime integer DEFAULT 60,
  businessHours text,
  signatureNote text,
  emailSupport text,
  invoicePrefix text DEFAULT 'HD',
  totalStocks bigint DEFAULT 10000000,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS public.products CASCADE;
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric(12, 0) NOT NULL,
  stock integer DEFAULT 0,
  rewardPoints integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products (name);

DROP TABLE IF EXISTS public.packages CASCADE;
CREATE TABLE public.packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sessions integer NOT NULL DEFAULT 1,
  price numeric(12, 0) NOT NULL,
  rewardPoints integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_packages_name ON public.packages (name);

DROP TABLE IF EXISTS public.staffs CASCADE;
CREATE TABLE public.staffs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text,
  baseSalary integer DEFAULT 0,
  serviceComm integer DEFAULT 0,
  consultComm integer DEFAULT 0,
  stocks numeric DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_staffs_phone ON public.staffs (phone);

DROP TABLE IF EXISTS public.customers CASCADE;
CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text UNIQUE,
  referral_code text,
  referred_by text,
  referral_rewarded boolean DEFAULT false,
  my_packages jsonb DEFAULT '[]',
  points integer DEFAULT 0,
  stocks numeric DEFAULT 0,
  history jsonb DEFAULT '[]',
  shares numeric DEFAULT 0,
  balance numeric DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers (phone);

DROP TABLE IF EXISTS public.appointments CASCADE;
CREATE TABLE public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_phone text,
  service text NOT NULL,
  ktv text,
  date date,
  time text,
  price numeric(12, 0) DEFAULT 0,
  status text DEFAULT 'Chờ phục vụ',
  note text,
  is_reminded boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  shared_update boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_appointments_customer_phone ON public.appointments (customer_phone);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON public.appointments (status);

DROP TABLE IF EXISTS public.online_orders CASCADE;
CREATE TABLE public.online_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text,
  customer_phone text,
  order_type text,
  item_id bigint,
  item_name text,
  quantity integer DEFAULT 1,
  total_price numeric(12, 0) DEFAULT 0,
  reward_points integer DEFAULT 0,
  payment_method text,
  payment_proof text,
  status text DEFAULT 'pending',
  order_date date,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_online_orders_status ON public.online_orders (status);
CREATE INDEX IF NOT EXISTS idx_online_orders_customer_phone ON public.online_orders (customer_phone);

DROP TABLE IF EXISTS public.customer_treatment_logs CASCADE;
CREATE TABLE public.customer_treatment_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL,
  date date,
  service text,
  staff text,
  note text,
  images jsonb DEFAULT '{}',
  skinCondition text,
  productsUsed text,
  nextStep text,
  sessionProgress text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_treatment_logs_customer_id ON public.customer_treatment_logs (customer_id);

DROP TABLE IF EXISTS public.chat_messages CASCADE;
CREATE TABLE public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_type text,
  sender text,
  target_phone text,
  text text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_target_phone ON public.chat_messages (target_phone);

DROP TABLE IF EXISTS public.share_transactions CASCADE;
CREATE TABLE public.share_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL,
  type text,
  amount numeric DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_share_transactions_customer_id ON public.share_transactions (customer_id);

DROP TABLE IF EXISTS public.employees CASCADE;
CREATE TABLE public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  phone text,
  role text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS public.attendance CASCADE;
CREATE TABLE public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL,
  check_in timestamptz,
  check_out timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (employee_id) REFERENCES public.employees (id) ON DELETE CASCADE
);

-- Update timestamp trigger helper
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Enable Row Level Security and add policies for anonymous access
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_settings ON public.settings;
CREATE POLICY allow_anon_settings ON public.settings
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_products ON public.products;
CREATE POLICY allow_anon_products ON public.products
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_packages ON public.packages;
CREATE POLICY allow_anon_packages ON public.packages
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.staffs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_staffs ON public.staffs;
CREATE POLICY allow_anon_staffs ON public.staffs
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_customers ON public.customers;
CREATE POLICY allow_anon_customers ON public.customers
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_appointments ON public.appointments;
CREATE POLICY allow_anon_appointments ON public.appointments
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.online_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_online_orders ON public.online_orders;
CREATE POLICY allow_anon_online_orders ON public.online_orders
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.customer_treatment_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_customer_treatment_logs ON public.customer_treatment_logs;
CREATE POLICY allow_anon_customer_treatment_logs ON public.customer_treatment_logs
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_chat_messages ON public.chat_messages;
CREATE POLICY allow_anon_chat_messages ON public.chat_messages
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.share_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_share_transactions ON public.share_transactions;
CREATE POLICY allow_anon_share_transactions ON public.share_transactions
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_employees ON public.employees;
CREATE POLICY allow_anon_employees ON public.employees
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_attendance ON public.attendance;
CREATE POLICY allow_anon_attendance ON public.attendance
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- Attach trigger to tables with updated_at
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_products') THEN
    CREATE TRIGGER trigger_update_timestamp_products
    BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_packages') THEN
    CREATE TRIGGER trigger_update_timestamp_packages
    BEFORE UPDATE ON public.packages
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_staffs') THEN
    CREATE TRIGGER trigger_update_timestamp_staffs
    BEFORE UPDATE ON public.staffs
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_customers') THEN
    CREATE TRIGGER trigger_update_timestamp_customers
    BEFORE UPDATE ON public.customers
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_appointments') THEN
    CREATE TRIGGER trigger_update_timestamp_appointments
    BEFORE UPDATE ON public.appointments
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_online_orders') THEN
    CREATE TRIGGER trigger_update_timestamp_online_orders
    BEFORE UPDATE ON public.online_orders
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_settings') THEN
    CREATE TRIGGER trigger_update_timestamp_settings
    BEFORE UPDATE ON public.settings
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_employees') THEN
    CREATE TRIGGER trigger_update_timestamp_employees
    BEFORE UPDATE ON public.employees
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_update_timestamp_attendance') THEN
    CREATE TRIGGER trigger_update_timestamp_attendance
    BEFORE UPDATE ON public.attendance
    FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Enable Row Level Security and add policies for anonymous access
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_settings ON public.settings;
CREATE POLICY allow_anon_settings ON public.settings
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_products ON public.products;
CREATE POLICY allow_anon_products ON public.products
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_packages ON public.packages;
CREATE POLICY allow_anon_packages ON public.packages
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.staffs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_staffs ON public.staffs;
CREATE POLICY allow_anon_staffs ON public.staffs
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_customers ON public.customers;
CREATE POLICY allow_anon_customers ON public.customers
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_appointments ON public.appointments;
CREATE POLICY allow_anon_appointments ON public.appointments
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.online_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_online_orders ON public.online_orders;
CREATE POLICY allow_anon_online_orders ON public.online_orders
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.customer_treatment_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_customer_treatment_logs ON public.customer_treatment_logs;
CREATE POLICY allow_anon_customer_treatment_logs ON public.customer_treatment_logs
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_chat_messages ON public.chat_messages;
CREATE POLICY allow_anon_chat_messages ON public.chat_messages
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.share_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_share_transactions ON public.share_transactions;
CREATE POLICY allow_anon_share_transactions ON public.share_transactions
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_employees ON public.employees;
CREATE POLICY allow_anon_employees ON public.employees
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_anon_attendance ON public.attendance;
CREATE POLICY allow_anon_attendance ON public.attendance
  FOR ALL
  USING (auth.role() IN ('authenticated', 'anon'))
  WITH CHECK (auth.role() IN ('authenticated', 'anon'));
